version: "3.9"
services:
  parser_db:
    ports:
      - 5432:5432

  rabbit:
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    ports:
      - 6379:6379

  parser_api:
    volumes:
      - ${PWD}/src:/app/src