# Generated by Django 5.1.1 on 2024-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="HabrSourceURLs",
            name="is_enable",
            field=models.BooleanField(default=True),
        ),
    ]
